### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by HaFred** [iliiliiliili/KittiViewer-plus#1]
Hi, I am running into this issue after all the dependencies are installed as in readme.
```
nvcc -std=c++11 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_75 --expt-relaxed-constexpr
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
```
I did some search, it seems like these packages need to be installed solely with `conda` or `pip`?

**Comment by iliiliiliili** [comment]
Hi, thank you for your interest in this work. Do you have gcc installed in your environment? Also, I will take a look, it seems like the part that requires this operation can be removed from the code.
