### ISSUE TITLE
Dose this project support http server like the original kittiviewer?

### ISSUE THREAD

**Issue by 2892510130** [iliiliiliili/KittiViewer-plus#4]
Hi, I use 'python http.server' to open the website, but it's a blank page.  Dose this project support http server like the original kittiviewer?

**Comment by iliiliiliili** [comment]
Hi, I have worked and updated the QT interface only as I never used the http interface, so most likely it has some broken API calls

**Comment by 2892510130** [comment]
Thanks, I just find it annoying to repeatedly download data from the server, lol.
